
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SampleClassification.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SampleClassification.ModelInput sampleData = new SampleClassification.ModelInput()
            {
                MachineID = @"M2",
                Temperature = 61F,
                Vibration = 3F,
                HoursRun = 4310F,
                Pressure = 116F,
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual DidItFail with predicted DidItFail from sample data...\n\n");


            Console.WriteLine($"MachineID: {@"M2"}");
            Console.WriteLine($"Temperature: {61F}");
            Console.WriteLine($"Vibration: {3F}");
            Console.WriteLine($"HoursRun: {4310F}");
            Console.WriteLine($"Pressure: {116F}");
            Console.WriteLine($"DidItFail: {0F}");


            var sortedScoresWithLabel = SampleClassification.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
